[mgr]
cwd = { fg = "#CECDC3", bold = true }

# Hovered
hovered = { fg = "#131519", bg = "#9BBFBF" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#AD8301", reversed = true }
find_position = { fg = "#575653", bold = true, italic = true }

# Marker
marker_copied = { fg = "#131519", bg = "#C5E1A5" }
marker_cut = { fg = "#131519", bg = "#E0A4A4" }
marker_marked = { fg = "#131519", bg = "#BCA4E0" }
marker_selected = { fg = "#131519", bg = "#E0DEA4" }

# Count
count_copied = { fg = "#879A39", bold = true, reversed = true }
count_cut = { fg = "#D14D41", bold = true, reversed = true }
count_selected = { fg = "#3AA99F", bold = true, reversed = true }

# Border
border_symbol = "│"
border_style = { fg = "#131519" }

[tabs]
active = { fg = "#131519", bg = "#9BBFBF", bold = true }
inactive = { fg = "#DFDFDD", bg = "#131519" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
# Normal mode
normal_main = { fg = "#131519", bg = "#9BBFBF", bold = true }
normal_alt = { fg = "#DFDFDD", bg = "#56606D" }

# Select mode
select_main = { fg = "#131519", bg = "#BCA4E0", bold = true }
select_alt = { fg = "#131519", bg = "#BCA4E0" }

# Unset mode
unset_main = { fg = "#100F0F", bg = "#E0DEA4", bold = true }
unset_alt = { fg = "#3AA99F", bg = "#E0DEA4" }

[status]
overall = { fg = "#9BBFBF" }

# Permissions
perm_type = { fg = "#4385BE" }
perm_read = { fg = "#D0A215" }
perm_write = { fg = "#D14D41" }
perm_exec = { fg = "#879A39" }
perm_sep = { fg = "#878580" }

# Progress
progress_label = { fg = "#100F0F" }
progress_normal = { fg = "#3AA99F", bg = "#1C6C66" }
progress_error = { bg = "#D14D41" }

[which]
cols = 3
mask = { bg = "#E0DEA4" }
cand = { fg = "#131519", bold = true }
rest = { fg = "#131519", italic = true }
desc = { fg = "#131519" }
separator = " "
separator_style = { }

[confirm]
border = { fg = "#E0A4A4" }
title = { fg = "#E0A4A4", bold = true }
content = { fg = "#DFDFDD", bold = true }
list = { fg = "#CECDC3" }
btn_yes = { fg = "#DFDFDD", bg = "#403E3C", bold = true }
btn_no = { fg = "#DFDFDD", bg = "#282726" }

[spot]
border = { fg = "#9BBFBF" }
title = { fg = "#9BBFBF", bold = true }
tbl_col = { fg = "#E0DEA4" }
tbl_cell = { bg = "#E0DEA4" }

[notify]
title_info = { fg = "#C5E1A5" }
title_warn = { fg = "#E0DEA4" }
title_error = { fg = "#E0A4A4" }

[pick]
border = { fg = "#403E3C", bold = true }
active = { fg = "#CECDC3" }
inactive = { fg = "#878580" }

[input]
border = { fg = "#9BBFBF" }
title = { fg = "#9BBFBF", bold = true }
value = { fg = "#DFDFDD" }
selected = { bg = "#9BBFBF" }

[cmp]
border = { fg = "#9BBFBF", bold = true }
active = { fg = "#131519", bg = "#9BBFBF" }
inactive = { fg = "#9BBFBF" }

[tasks]
border = { fg = "#9BBFBF" }
title = { fg = "#9BBFBF", bold = true }
hovered = { bg = "#56606D" }

[help]
on = { fg = "#E0DEA4" }
run = { fg = "#C5E1A5" }
desc = { fg = "#DFDFDD", italic = true }
hovered = { bg = "#56606D" }
footer = { fg = "#9BBFBF", bg = "#282726", bold = true }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#8B7EC8" },

  # Media
  { mime = "video/*", fg = "#D0A215" },
  { mime = "audio/*", fg = "#D0A215" },

  # Broken symbolic link
  { name = "*", is = "orphan", fg = "#E0A4A4", crossed = true },
  { name = "*/", is = "orphan", fg = "#E0A4A4", crossed = true },

  # Symbolic links
  { name = "*", is = "link", fg = "#BCA4E0" },
  { name = "*/", is = "link", fg = "#BCA4E0" },

  # Executable
  { name = "*", is = "exec", fg = "#879A39" },

  # Empty files
  { mime = "inode/empty", fg = "#575653" },

  # Fallback
  { name = "*", fg = "#DFDFDD" },
  { name = "*/", fg = "#9BBFBF" }
]
